//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Editor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Editor.ITodoEditor")]
    public interface ITodoEditor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoEditor/GetList", ReplyAction="http://tempuri.org/ITodoEditor/GetListResponse")]
        string GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoEditor/GetList", ReplyAction="http://tempuri.org/ITodoEditor/GetListResponse")]
        System.Threading.Tasks.Task<string> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoEditor/GetTask", ReplyAction="http://tempuri.org/ITodoEditor/GetTaskResponse")]
        string GetTask(TodoListLib.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoEditor/GetTask", ReplyAction="http://tempuri.org/ITodoEditor/GetTaskResponse")]
        System.Threading.Tasks.Task<string> GetTaskAsync(TodoListLib.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoEditor/InitializeList", ReplyAction="http://tempuri.org/ITodoEditor/InitializeListResponse")]
        void InitializeList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoEditor/InitializeList", ReplyAction="http://tempuri.org/ITodoEditor/InitializeListResponse")]
        System.Threading.Tasks.Task InitializeListAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITodoEditorChannel : Client.Editor.ITodoEditor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodoEditorClient : System.ServiceModel.ClientBase<Client.Editor.ITodoEditor>, Client.Editor.ITodoEditor {
        
        public TodoEditorClient() {
        }
        
        public TodoEditorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TodoEditorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoEditorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoEditorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<string> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public string GetTask(TodoListLib.Task task) {
            return base.Channel.GetTask(task);
        }
        
        public System.Threading.Tasks.Task<string> GetTaskAsync(TodoListLib.Task task) {
            return base.Channel.GetTaskAsync(task);
        }
        
        public void InitializeList(string username) {
            base.Channel.InitializeList(username);
        }
        
        public System.Threading.Tasks.Task InitializeListAsync(string username) {
            return base.Channel.InitializeListAsync(username);
        }
    }
}
